services:
  ambev.developerevaluation.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"

  ambev.developerevaluation.database:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-developer_evaluation}
      - POSTGRES_USER=${POSTGRES_USER:-developer}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password}

  ambev.developerevaluation.nosql:
    ports:
      - "27017:27017"

  ambev.developerevaluation.cache:
    ports:
      - "6379:6379"
